---
title: "PCA_plants.rmd"
author: "Ioannis D. Kampouris"
date: "2025-02-04"
output: html_document
---
```{r}
source(paste0("~/MS3_correlation_network/functions_load.R"))
library(ggplot2) #ggplot2: Fancy graphs
library(ggpubr) #ggplot expansion for more fancy graphs
library(readxl) # upload files  
library(readr) # read the files
library(tidyr) # Data handling
library(RColorBrewer) # Colours for fancy graphs
library(tibble)# Data handling: rownames/columnanmes
library(stringr) # Manipulate strings
library(dplyr)
library(reshape2)
library(vegan)
library(ggrepel)
```

```{r}

deltacts= read_excel(paste0("~/LTE2020_geneExpression_deltaCT.xlsx"))%>% 
  select(., ID=TREATMENT, everything())
Growth_stats= read_excel(paste0("~/LTE2020_growth_statistics.xlsx"))%>%select(ID, VALUE)
np_content= read_excel(paste0("~/LTE2020_plant_nutrient_content.xlsx"))


stress_CT_RW= read_excel(paste0("~/Hormones_and_Stress_Ind_Central_and_RW.xlsx"), 
    sheet = "Stress_Indicator")%>%
  mutate(ID=paste0(TILLAGE_TYPE,"-",FERTILIZATION,"-",Bms,"-",REPLICATE ))%>%
  filter(PLOT=="central")%>%
  filter(LOCATION=="shoot")

stress_CT_RW2=stress_CT_RW[,c(1, 10:ncol(stress_CT_RW))]

HSI_CT_RW=read_excel(paste0("~/Hormones_and_Stress_Ind_Central_and_RW.xlsx"))%>%
  mutate(ID=paste0(TILLAGE_TYPE,"-",FERTILIZATION,"-",Bms,"-",REPLICATE ))%>%
  filter(PLOT=="central")%>%
  filter(LOCATION=="shoot")
HSI_CT_RW2=HSI_CT_RW[,c(1, 10:ncol(HSI_CT_RW))]

```

```{r}


joined=full_join(np_content,deltacts, by="ID")%>% 
  full_join(., HSI_CT_RW2, by="ID")%>%
  full_join(., stress_CT_RW2, by="ID")%>%
    full_join(Growth_stats%>%select(ID, SDM=VALUE), by="ID")
joined=as.data.frame(joined)
rownames(joined)=joined$ID
PCA1= prcomp((joined[,11:75,drop=F]), scale = T)
dist1c=scores <- as.data.frame(PCA1$x)
loadings <- as.data.frame(PCA1$rotation)
dist1d=cbind(dist1c[joined$ID,], joined[,1:10])%>%as.data.frame()

dist1d$BENEFICIALS=gsub("BMs","BMc",dist1d$BENEFICIALS)
dist1d$BENEFICIALS=factor(dist1d$BENEFICIALS, levels=c("Ctrl","BMc"))
```
```{r}
plot1=
ggplot(dist1d, aes(x=PC1, y=PC2))+geom_point( size=10, aes( colour=BENEFICIALS, shape=FERTILIZATION ))+
  stat_ellipse(aes( colour=BENEFICIALS,group=BENEFICIALS ))+ 
  scale_shape_manual( name="N-Fertilization_Intensity: ",  values = c(16,17))+
  scale_colour_manual(name="",values=c( "#146eb4","#ff9900"))+
  theme_bw()+
  theme(legend.position = "top", 
    axis.text.y = element_text( size=45, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 45, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=45, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=45, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 45, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=55, face="bold", colour = "black"))+
  xlab(paste0("PC1[", round(100*PCA1$sdev[1]/sum(PCA1$sdev),2),"]"))+
  ylab(paste0("PC2[", round(100*PCA1$sdev[2]/sum(PCA1$sdev),2),"]"))+
  geom_segment(data = loadings, aes(x = 0, y = 0, xend = PC1*25, yend = PC2*25),
               arrow = arrow(length = unit(0.2, "cm")), color = "darkred") +
 geom_label_repel(data = loadings, aes(x = PC1*25, y = PC2*25, label = rownames(loadings)),
            color = "black",  max.iter = 1000000, vjust = -0.5,
            max.overlaps = 1000000, size=6,
  nudge_x =-0.25 ,
  nudge_y = -0.25,
  force=1000) 


pdf( "PCA.plot1.pdf", height = 2000, width = 15000)
print(plot1)
dev.off()
ggsave(plot1,file="PCA.plot.pdf", height = 15, width = 30,limitsize = F)

```


```{r}
plot1=
ggplot(dist1d, aes(x=PC1, y=PC2))+geom_point( size=10, aes( colour=BENEFICIALS, shape=FERTILIZATION ))+
  stat_ellipse(aes( colour=BENEFICIALS,group=BENEFICIALS ))+ 
  scale_shape_manual( name="N-Fertilization_Intensity: ",  values = c(16,17))+
  scale_colour_manual(name="",values=c( "#146eb4","#ff9900"))+
  theme_bw()+
  theme(legend.position = "top", 
    axis.text.y = element_text( size=45, face = "bold", colour="black")) +
  theme(axis.text.x = element_text(size = 45, face = "bold", colour="black")) +
  theme(legend.text = element_text( size=45, face="bold", colour = "black")) + 
  theme( axis.title.y = element_text( size=45, face = "bold", colour="black")) + 
  theme(axis.title.x = element_text(size = 45, face = "bold", colour="black")) +
  theme(legend.title =  element_text( size=55, face="bold", colour = "black"))+
  xlab(paste0("PC1[", round(100*PCA1$sdev[1]/sum(PCA1$sdev),2),"]"))+
  ylab(paste0("PC2[", round(100*PCA1$sdev[2]/sum(PCA1$sdev),2),"]"))

ggsave(plot1,file="PCA_without_rows.plot.pdf", height = 15, width = 30,limitsize = F)

```



```{r}
pca_load <- 
  as_tibble(pca_values$rotation, rownames = 'variable')
PCA2=vegdist(joined[,11:75,drop=F], method = "euclidean")
permanova1=adonis2(PCA2~BENEFICIALS*FERTILIZATION,  data=dist1d, permutations = 99999, by="terms")

permutest(
  betadisper(PCA1, dist1d$BENEFICIALS))


permutest(
  betadisper(PCA1, dist1d$FERTILIZATION))


permutest(
  betadisper(PCA1, paste0(dist1d$BENEFICIALS, dist1d$FERTILIZATION) ))

```

```{r}

list_of_nutrients=list()
for(i in colnames(np_content[,11:22])){
  print(i )
file1=np_content
file1$var=as.numeric( np_content[,i,drop=T])
file1=as.data.frame(file1)
file2=lm(file1$var ~file1$BENEFICIALS*file1$FERTILIZATION)  
file3=anova(file2)
df1=data.frame(Nutrient=colnames(np_content[,i,drop=F]),
               FFert=file3[2,4], FBMc=file3[1,4],
               PFert=file3[2,5],
               PBMc=file3[1,5],
               Fint=file3[3,4],
               Pint=file3[3,5],
                shap=shapiro.test(resid(file2))[[2]]  )


list_of_nutrients=rbind(
list_of_nutrients, df1)
}
write.csv(
  file = "MS3ANOVANutrient.csv", list_of_nutrients)
```

```{r}
root_CT_RW= read_excel(paste0("~/Hormones_and_Stress_Ind_Central_and_RW.xlsx"))%>%
  mutate(ID=paste0(TILLAGE_TYPE,"-",FERTILIZATION,"-",Bms,"-",REPLICATE ))%>%
  filter(PLOT=="central")%>%
  filter(LOCATION=="root")
root_CT_RW2=root_CT_RW[,c(1, 10:ncol(root_CT_RW))]
names_col=data.frame(name= paste0("Root-", colnames(root_CT_RW2[,2:ncol(root_CT_RW2)])))
colnames(root_CT_RW2)<-c("ID",names_col$name)

library(MASS)
b <- MASS::boxcox(lm(JA ~ 1, data = root_CT_RW))
# Exact lambda
lambda <- b$x[which.max(b$y)]
lambda
root_CT_RW$newJA= (root_CT_RW$JA^lambda - 1) / lambda
model1=lm(scale((JA))~Bms*FERTILIZATION, data=root_CT_RW)

model2=lm((SA)~Bms*FERTILIZATION, data=root_CT_RW)

```