---
title: "cherryonthetop.rmd"
author: "Ioannis D. Kampouris"
date: "2023-05-13"
output: pdf_document
pandoc_args: --listings
includes:
in_header: preamble.tex
editor_options: 
  chunk_output_type: inline
---

```{r}
library(readxl) # upload files  
library(readr) # read the files
library(tidyr) # Data handling
library(RColorBrewer) # Colours for fancy graphs
library(tibble)# Data handling: rownames/columnanmes
library(stringr) # Manipulate strings
library(dplyr)
library(reshape2)
library(psych)
library(corrplot)
```

*LOAD THE DATA*
```{r}
deltacts= read_excel(paste0("/home/ioannis.kampouris/",
"DiControl_JKI_Phase3_repos/",
"MS3_correlation_network/LTE2020_geneExpression_deltaCT.xlsx"))%>% 
  select(., ID=TREATMENT, everything())
np_content= read_excel(paste0("/home/ioannis.kampouris/",
"DiControl_JKI_Phase3_repos/",
"MS3_correlation_network/LTE2020_plant_nutrient_content.xlsx"))

joined=full_join(np_content[,c(1,14:22)]%>%as.data.frame(),
                 deltacts, by="ID")


joined=joined[,-1]


correlations= psych::corr.test(as.matrix( joined), method =  "pearson",adjust="BH" )
corrplot(correlations$r, p.mat = correlations$p, method = 'circle', type = 'lower', insig='blank',diag=FALSE)
plot1= corrplot(correlations$r, p.mat = correlations$p,  insig='blank',diag=FALSE,  type="full", tl.col="black",order="hclust", cl.cex=3)
```
